<?php
$basePath = $this->basePath() . '/../module/SocialogAdmin/public';

$this->headLink()
	->appendStylesheet($basePath . '/vendor/wysihtml5/bootstrap-wysihtml5.css');
		
$this->headScript()
	->appendFile($basePath . '/vendor/wysihtml5/wysihtml5-0.3.0.min.js')
	->appendFile($basePath . '/vendor/wysihtml5/bootstrap-wysihtml5.js');


$form = $this->form;
$form->prepare();
?>

<div class="block">

	<div class="block-head">
		<h2><?php echo $this->title; ?></h2>
	</div>

	<div class="block-content">
		<?php echo $this->form()->openTag($form); ?>
		<?php echo $this->formHidden($form->get('id')); ?>
		<div class="control-group">
			<label class="control-label" for="inputEmail">Title</label>
			<div class="controls">
				<?php echo $this->formText($form->get('title')); ?>
				<span class="help-inline"></span>
				<?php echo $this->formElementErrors($form->get('title')); ?>
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="inputEmail">Content</label>
			<div class="controls">
				<?php echo $this->formTextarea($form->get('content')); ?>
				<?php echo $this->formElementErrors($form->get('content')); ?>
			</div>
		</div>

		<div class="control-group">
			<div class="controls">
				<?php echo $this->formSubmit($form->get('submit')); ?>
			</div>
		</div>

		<?php echo $this->form()->closeTag(); ?>
	</div>

</div>
<script type="text/javascript">
$(function(){
	$('textarea[name=content]').wysihtml5();
});
</script>

