<?php
$this->triggerEvent('post.edit');

$form = $this->form;
$form->prepare();
?>

<div class="block">

    <div class="block-head">
        <h2><?php echo $this->title; ?></h2>
    </div>

    <div class="block-content">
        
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formHidden($form->get('id')); ?>
        <div class="control-group">
            <label class="control-label" for="title">Title</label>
            <div class="controls">
                <?php echo $this->formText($form->get('title')); ?>
                <span class="help-inline"></span>
                <?php echo $this->formElementErrors($form->get('title')); ?>
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="content">Content</label>
            <div class="controls">
                <?php echo $this->formTextarea($form->get('content')); ?>
                <?php echo $this->formElementErrors($form->get('content')); ?>
            </div>
        </div>

        <!-- Status -->
		<div class="control-group">
			<label class="control-label" for="content">Status</label>
			<div class="controls">
                <select>
                  <option>Published</option>
                  <option>Draft</option>
                  <option>3</option>
                  <option>4</option>
                  <option>5</option>
                </select>
			</div>
		</div>

        <div class="control-group">
            <div class="controls">
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>

</div>