<div class="block">

	<div class="block-head">
		<h2>Login</h2>
	</div>

	<div class="block-content">

		<form class="form-horizontal" action="" method="POST">

			<div class="control-group">
				<label class="control-label" for="inputEmail">Email</label>
				<div class="controls">
					<input type="text" id="inputEmail" placeholder="Email" name="email">
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="inputPassword">Password</label>
				<div class="controls">
					<input type="password" id="inputPassword" placeholder="Password" name="password">
				</div>
			</div>

			<div class="control-group">
				<div class="controls">
<!--					
						<label class="checkbox">
						<input type="checkbox"> Remember me
					</label>
-->
					<button type="submit" class="btn">Sign in</button>
				</div>
			</div>
		</form>
	</div>
</div>

